repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-xml
      - id: check-toml
      - id: check-docstring-first
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: mixed-line-ending
      - id: name-tests-test
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        args: [feat, fix, docs, style, refactor, test, chore]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
        args: ['-i']
        files: \.(cpp|h)$
  - repo: local
    hooks:
      - id: check-file-headers
        name: Check File Headers
        entry: ./scripts/check_file_headers.sh
        language: script
